# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codenerix_products', '0001_initial'),
        ('codenerix_corporate', '0001_initial'),
        ('codenerix_pos', '0001_initial'),
        ('codenerix_payments', '0001_initial'),
        ('codenerix_invoicing', '0002_auto_20180117_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='posproduct',
            name='product_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posproducts', to='codenerix_products.ProductFinal', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='posplant',
            name='billing_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posplants', to='codenerix_invoicing.BillingSeries', verbose_name='Billing series'),
        ),
        migrations.AddField(
            model_name='posplant',
            name='corporate_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posplants', to='codenerix_corporate.CorporateImage', verbose_name='Corporate image'),
        ),
        migrations.AddField(
            model_name='posoperator',
            name='pos',
            field=models.ManyToManyField(related_name='pos_operators', to='codenerix_pos.POS', verbose_name='POS'),
        ),
        migrations.AddField(
            model_name='poslog',
            name='pos',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='codenerix_pos.POS', verbose_name='POS'),
        ),
        migrations.AddField(
            model_name='poslog',
            name='poshw',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='codenerix_pos.POSHardware', verbose_name='POS'),
        ),
        migrations.AddField(
            model_name='poshardware',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardwares', to='codenerix_pos.POS', verbose_name='POS'),
        ),
        migrations.AddField(
            model_name='pos',
            name='group_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poss', to='codenerix_pos.POSGroupProduct', verbose_name='Group product'),
        ),
        migrations.AddField(
            model_name='pos',
            name='hardware',
            field=models.ManyToManyField(blank=True, null=True, related_name='poss', to='codenerix_pos.POSHardware', verbose_name='Hardware it can use'),
        ),
        migrations.AddField(
            model_name='pos',
            name='payments',
            field=models.ManyToManyField(blank=True, related_name='poss', to='codenerix_payments.PaymentRequest', verbose_name='Payments'),
        ),
    ]
