# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posslot',
            name='pos_x',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Pos X'),
        ),
        migrations.AlterField(
            model_name='posslot',
            name='pos_y',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Pos Y'),
        ),
    ]
