# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posproduct',
            name='group_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posproducts', to='codenerix_pos.POSGroupProduct', verbose_name='Group Product'),
        ),
    ]
