# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-17 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codenerix_pos', '0002_auto_20180117_1628'),
        ('codenerix_storages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='storage_query',
            field=models.ManyToManyField(blank=True, null=True, related_name='poss_storage_query', to='codenerix_storages.Storage', verbose_name='Storages where you can consult'),
        ),
        migrations.AddField(
            model_name='pos',
            name='storage_stock',
            field=models.ManyToManyField(blank=True, null=True, related_name='poss_storage_stock', to='codenerix_storages.Storage', verbose_name='Storages where the stock is subtracted'),
        ),
        migrations.AddField(
            model_name='pos',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poss', to='codenerix_pos.POSZone', verbose_name='Zone'),
        ),
        migrations.AlterUniqueTogether(
            name='posproduct',
            unique_together=set([('group_product', 'product_final')]),
        ),
        migrations.AlterUniqueTogether(
            name='poshardware',
            unique_together=set([('pos', 'kind', 'name')]),
        ),
    ]
