# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_pos', '0002_auto_20170719_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshardware',
            name='kind',
            field=models.CharField(choices=[(b'T', 'Ticket'), (b'D', 'DNI'), (b'C', 'Cash'), (b'S', 'Signature'), (b'Q', 'Query')], max_length=1, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='poshardware',
            name='pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardwares', to='codenerix_pos.POS', verbose_name='Hardware'),
        ),
    ]
