# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-30 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_pos', '0016_poshardware_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='channel',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='Channel'),
        ),
    ]
