# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_pos', '0022_auto_20170818_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshardware',
            name='pos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardwares', to='codenerix_pos.POS', verbose_name='POS'),
        ),
    ]
