# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_pos', '0025_auto_20170918_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='commit',
            field=models.CharField(blank=True, default='LATEST', editable=False, max_length=40, null=True, verbose_name='Commit'),
        ),
    ]
