# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-22 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix_pos', '0029_merge_20170921_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='commit',
            field=models.CharField(blank=True, default='LATEST', max_length=40, null=True, verbose_name='Commit'),
        ),
    ]
